### ISSUE TITLE
First login and initial startup

### ISSUE THREAD

**Issue by vaaralav** [DependencyTrack/frontend#1]
Add support for changing the initial admin password on first login. See the solution in existing UI: https://github.com/DependencyTrack/dependency-track/blob/c4f469bf735731a02e57e549fa9dda89abfd8977/src/main/webapp/assets/common.js#L175-L223.

> An administrative account is created on initial startup with the following credentials:
>
>username: admin
>password: admin
>Upon first login, the admin user is required to change the password.
> 
> https://docs.dependencytrack.org/getting-started/initial-startup/

**Comment by Pinqvin** [comment]
I can have a look at this issue

**Comment by Pinqvin** [comment]
This issue was fixed in PR #7 and can be closed
