### ISSUE TITLE
Unable to create more than 1 project from the UI without switching views

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/frontend#1025]
### Current Behavior

I was doing some testing to see if we want to upgrade to 4.12.0 and tried to create several projects in the UI. After creating a new project, the overlay for a new project does open, validations do work, but clicking the 'create'-button doesn't do anything. The button is active, it just doesn't do anything. No errors in the logs either.
Switching from the project-view to a different view and then back, makes the creation work again, but again only for a single new project!

### Steps to Reproduce

1. In the UI, create a new project
2. Create another new project

### Expected Behavior

I expect to be able to create new projects without having to switch views, just like before in 4.11.x

### Dependency-Track Frontend Version

4.12.0

### Browser

Mozilla Firefox

### Browser Version

130.0.1

### Operating System

macOS

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by rkg-mm** [comment]
Reason:
in ProjectCreateProjectModal.vue in resetValues function, the object assigned to this.project needs an additional line:
`team: [],`
