### ISSUE TITLE
National Vulnerability Database (NVD) properties are not persisted

### ISSUE THREAD

**Issue by mhoffmann-attempto** [DependencyTrack/frontend#137]
I recognized a that National Vulnerability Database properties are not saved to the API Server.

### Current Behavior:
Try to Change the National Vulnerability Database properties has no effect

### Steps to Reproduce:
0. the Mirroring was disabled before
1. go to Administration: National Vulnerability Database
2. Enable National Vulnerability Database mirroring
3. Insert a value for NVD Feeds URL: e.g. https://nvd.nist.gov/feeds
4. Click on update.
5. go to another page and return to National Vulnerability Database -> properties are gone

### Expected Behavior:
the changed properties of National Vulnerability Database are saved correctly

### Environment:
  
  - Dependency-Track Version: 4.4.2
  - Client Browser: Firefox / Chrome / Safari
  - Client O/S: MacOS 12.3.1

### Additional Details:
I had a look into the API request to change the properties.
The values where null! (Debuged with Firefox Dev-Tools) Maybe it is a hint....

Post to:  
`https://<DEP-TRACK-SERVER>/api/v1/configProperty/aggregate`
Body:
`[{"groupName":"vuln-source","propertyName":"nvd.enabled","propertyValue":null},{"groupName":"vuln-source","propertyName":"nvd.feeds.url","propertyValue":null}]`

**Comment by frost9i** [comment]
Spotted the same issue and went to Q&A.
https://github.com/DependencyTrack/dependency-track/discussions/1545

Thank you for taking it into planned work.

**Comment by RazorTheBeaver** [comment]
Hello @stevespringett,
Can this issue lead dependency track to not sync the NVD anymore ? 
Best regards,
RazorTheBeaver

**Comment by frost9i** [comment]
Furthermore it can have larger impact:
![image](https://user-images.githubusercontent.com/25299818/163382340-11e19a21-4d65-4131-ac68-2ddbef35c77e.png)

![image](https://user-images.githubusercontent.com/25299818/163382346-7b8022de-18ee-44a1-b20e-cc5bc30a2a01.png)

**Comment by RazorTheBeaver** [comment]
Hi there,

A quick fix can be applied to make it run again.
Change the value manually inside the database then restart dependency track.
![image](https://user-images.githubusercontent.com/102231206/163574396-5c2b0321-9712-4784-9f91-6f1f84f7819a.png)
Best,
RazorTheBeaver

**Comment by frost9i** [comment]
Hey. Hope this will save someone his time:

```sql
UPDATE "CONFIGPROPERTY" SET "PROPERTYVALUE"='true' WHERE "PROPERTYNAME"='nvd.enabled';
UPDATE "CONFIGPROPERTY" SET "PROPERTYVALUE"='https://nvd.nist.gov/feeds' WHERE "PROPERTYNAME"='nvd.feeds.url';
SELECT * FROM "CONFIGPROPERTY";
```
Save to file cmd.sql

`PGPASSWORD='your_pass' psql -U pgown -d dtrack -f cmd.sql`
