### ISSUE TITLE
wrong and hard coded tooltip

### ISSUE THREAD

**Issue by stexandev** [DependencyTrack/frontend#161]
---
name: Defect Report
about: Create a report to help us improve
title: 'wrong and hard coded tooltip'
labels: 'in triage'
assignees: ''
---
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
The tooltip for email input in the email configuration test shows a wrong text. This text is hard coded.

### Steps to Reproduce:
- browse to Home/Administration/Configuration/Email
- click Configuration Test
- hover your mouse over the tooltip location at the end of the input field

### Expected Behavior:
tooltip reads something like "Enter an Email address the message is sent to."

### Environment:
  
  - Dependency-Track Version: 4.4.2

### Additional Details:
offending code:
https://github.com/DependencyTrack/frontend/blob/a3313a4f8d9cae223c8e82027986fa6a137861c0/src/views/administration/configuration/EmailTestConfigurationModal.vue#L10

**Comment by robertlagrant** [comment]
Confirmed in 4.5.0 as well:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/1766161/185917616-e5defd96-5474-4efd-b508-33527003eded.png">
