### ISSUE TITLE
How to find a component beeing vulnarable in the deep dependency tree?

### ISSUE THREAD

**Issue by kkretsch** [DependencyTrack/frontend#165]
I have a NodeJS project and it is runnin into a vulnerable component **hosted-git-info**.
That module is not used directly in the _package.json_ and not mentioned in the _package-lock.json_ neither.

Even when I open all tree views in DependencyTrack I cannot see such a package. How can I find the dependency tree to get that triggering module?

**Comment by rstmm** [comment]
See #85

**Comment by msymons** [comment]
@kkretsch, whilst awaiting Frontend UI improvement to the dependency graph, there is something you might try as a workaround;  manually inspect the BOM that was imported to give you the graph.

The BOM has all the dependency data you need, even if Dependency-Track is not yet displaying all levels of the tree.

**Comment by rkg-mm** [comment]
@msymons you can close this as fixed with #85
