### ISSUE TITLE
Clickable dependency graph items

### ISSUE THREAD

**Issue by bdovaz** [DependencyTrack/frontend#166]
I don't know if this behavior occurs in all packages ecosystems but at least in NuGet, it does.

This would be very useful since I don't know why the graph only expands up to 2 levels. The transitive dependencies in NuGet do not end there so the graph does not help to visualize the information in a complete way (I guess this would be another issue).

### Current Behavior:

If you try to click on an element, nothing happens.

![image](https://user-images.githubusercontent.com/950602/173617059-2230a5e1-a7d5-45b3-ac1a-4c6a6193c646.png)

### Proposed Behavior:

Clicking on each item will take you to its page. Example:

https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/6.0.0

I suppose that the relevant code it's here:

https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ProjectDependencyGraph.vue

**Comment by lsauer** [comment]
Hi,
I proposed something similar. Take a look
https://github.com/DependencyTrack/frontend/issues/212#event-7080824348


> I don't know if this behavior occurs in all packages ecosystems but at least in NuGet, it does.
> 
> This would be very useful since I don't know why the graph only expands up to 2 levels. The transitive dependencies in NuGet do not end there so the graph does not help to visualize the information in a complete way (I guess this would be another issue).
> 
> ### Current Behavior:
> If you try to click on an element, nothing happens.
> 
> ![image](https://user-images.githubusercontent.com/950602/173617059-2230a5e1-a7d5-45b3-ac1a-4c6a6193c646.png)
> 
> ### Proposed Behavior:
> Clicking on each item will take you to its page. Example:
> 
> https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/6.0.0
> 
> I suppose that the relevant code it's here:
> 
> https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ProjectDependencyGraph.vue

**Comment by rkg-mm** [comment]
@msymons this can be closed as nodes are clickable now and open the component in Dependency-Track. Also all levels are displayed now.

**Comment by bdovaz** [comment]
Still has bugs such as no horizontal scrolling (check the right size of the image with the icon cropped)

![image](https://github.com/DependencyTrack/frontend/assets/950602/b8fb5f18-8d22-4088-90fb-a67acdb68ba4)

**Comment by rkg-mm** [comment]
@bdovaz  Scrolling works by Drag & Drop with mouse
