### ISSUE TITLE
Show author of component in component details dialog

### ISSUE THREAD

**Issue by stephan-wolf-ais** [DependencyTrack/frontend#181]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:

No text field available

### Expected Behavior:

athor shall be shown in the frontend

### Environment:
  
  - Dependency-Track Version: 4.5
  - Client Browser: all
  - Client O/S: all

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nscuro** [comment]
Done with #182.
