### ISSUE TITLE
Project View Details Can Display Wrong Tags

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/frontend#188]
### Current Behavior:
After adding or removing tags from version X of project A, and then switching via dropdown to version Y of project A,  the tags for Y look fine...  but clicking "project details" lists the tags for version X.

### Steps to Reproduce:

- Navigate to any project that has 2 or more versions.  ie,version X of project A
- Click on "view details" for this version X and add and remove some tags (make a note of what the tags were, so you can restore them later!)
- Click Updateto save your tag changes
- Use dropdown to switch to version Y of project A
- Click on "view details" for this version Y and note that the tags match what you just configured for version X.  They are not the correct tags for Y.

### Expected Behavior:
Tags in "view details" match the actual tags on the project.

### Environment:
  
  - Dependency-Track Version: 4.5.0 (and also in 4.6.0 SNAPSHOT)
  - Client Browser:  Firefox 102
  - Client O/S: Windows 10

### Additional Details:
I tried to see if the same behaviour occurred for description and type.  It did  not.  All was OK with those.

**Comment by tmehnert** [comment]
> I tried to see if the same behaviour occurred for description and type. It did not. All was OK with those.

@msymons confirm, the defect caused by an initialization routine, which is specially for tags. So no other fields should be impacted by this specific error.
