### ISSUE TITLE
Building UI without source maps

### ISSUE THREAD

**Issue by robertlagrant** [DependencyTrack/frontend#192]
### Current Behavior:
UI is built with Source Maps enabled, creating a Docker image about 56MB in size (anecdotal on my laptop).

### Proposed Behavior:
UI is built without source maps, creating a Docker image about 35MB in size (anecdotal on my laptop).

While it can be useful to have source maps in production builds, it does feel like the already pretty efficient build could be made even better (62% of current size) if they were omitted.

**Comment by nscuro** [comment]
Great suggestion! 

Looks like this can be addressed with `productionSourceMap: false` in the Vue config: https://cli.vuejs.org/config/#productionsourcemap

**Comment by robertlagrant** [comment]
Yes that worked locally. I've raised a PR!
