### ISSUE TITLE
Login redirect doesn't work

### ISSUE THREAD

**Issue by llamahunter** [DependencyTrack/frontend#20]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:

When deep linking into a page in deptrack, you first get redirected to the login page (despite being logged in already), and then you get deposited into the overview page, rather than the deep link you were following.

### Steps to Reproduce:

- Log in to deptrack.
- Copy a deep link to some project.
- Paste link into a new browser tab

### Expected Behavior:

Go directly to the project page.

### Environment:
  
  - Dependency-Track Version: v3.8.0
  - Distribution: Docker
  - BOM Format & Version: SBOM?
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:

Login is configured to use LDAP

**Comment by stevespringett** [comment]
Looks like the initial load fails and redirects to login screen, but repasting the URL into the same tab works.

**Comment by llamahunter** [comment]
Also, the login page should send you back to the deep link after login is successful, not the Overview page.

**Comment by sephiroth-j** [comment]
@stevespringett: You can close this one as well after #47 has been merged.

**Comment by qhantom** [comment]
@stevespringett Can be closed can't it?
