### ISSUE TITLE
Vue.js / Application urls are not working properly behind a reverse proxy with a context path (context path is duplicated)

### ISSUE THREAD

**Issue by lsauer** [DependencyTrack/frontend#205]
The application is running on the path /dtrack/. Since almost all content is created by vue.js on the clientside rather on the server side, rewriting urls with the reverse proxy is quite futile.

The situation is as follows. the app is started from dtrack, but the js, etc resources are loaded from the root:
![image](https://user-images.githubusercontent.com/996117/181269240-a09b444a-9664-449a-9bbd-f2686d696bb9.png)

### Current Behavior:
When hovering over a component in Home > Project > <PROJECTNAME> the url appears correct
![image](https://user-images.githubusercontent.com/996117/181266120-1e9c03b4-5b88-4a5b-8aa2-fbe705fdaee0.png)

![image](https://user-images.githubusercontent.com/996117/181266917-83ac9f7c-6f93-4b4e-bab9-461f2b180c6c.png)
The same misbehaviour is also true for the tags
![image](https://user-images.githubusercontent.com/996117/181267202-67c38e12-7269-4e2a-bfd1-ee13b68a9c27.png)

The url is set in the DOM as ../dtrack/hash , which in principle is correct. However vue.js clearly has a event-handler on the element to route it and the router is forwarding to

basedomain/dtrack/dtrack/hash with a 404
![image](https://user-images.githubusercontent.com/996117/181267416-9dd38e64-6ab6-471c-a1d3-85432c74fdbe.png)

/components may also be affected. I cannot test this right now.

### Steps to Reproduce:
See above. Clicking the link

### Expected Behavior:
opening the same url as indicated by the browser url preview at the bottom-left.

### Environment:
  
  - Dependency-Track Version: 4.5
  - Distribution: Docker 
  - BOM Format & Version: - 
  - Database Server: H2
  - Browser: Chrome, Firefox latest

### Additional Details:

The context path has to be set in vue.js It has a function `getContextPath`

Since most of the UI's urls actually work I am assuming this is a small bug of this particular 'project' Router/Controller Configuration.

It would help tremendously if all the js,static,css etc... could be moved into ONE unique path, called `dtrack` for everyone. There are few downsides, but many upsides.

The Eventlistener is here in App.vue:

It is pushed to the router, where I guess it is filtered out as a non App-native link because Vue.js does not have a basepath

![image](https://user-images.githubusercontent.com/996117/181278250-0c63cef7-3e89-4b55-afdf-5207485d4e60.png)

I just saw, this was hinted here: https://github.com/DependencyTrack/dependency-track/discussions/1831#discussioncomment-3260735

**Comment by lsauer** [comment]
> Related to #153.
> 
> As mentioned in [DependencyTrack/dependency-track#1831 (reply in thread)](https://github.com/DependencyTrack/dependency-track/discussions/1831#discussioncomment-3260735), it's kind of a known issue, but we didn't have the time to look into it yet. If you'd like to contribute a fix, I think you'd make lots of other folks really happy!

The bug may only presents itself in the custom Project-controller , and you considered that if the basePath is kept relative than everything may work. Could you revisit the issue of a empty built-time basePath. https://github.com/DependencyTrack/frontend/issues/153#issuecomment-1137235933

All other controllers seam fine.  I cannot check the Component Controller since all components are empty. Do you need to create a portfolio or full internet connection? The DT in question is running in an air-gapped environment. What is the purpose of the Component Section? 

If it should list all Components that have ever been uploaded in various Projects then I have another problem.

**Comment by jeremytbrun** [comment]
I'm running into this issue as well. Would like to run this behind a reverse proxy but status prefetch content is not being handled appropriately.

**Comment by nscuro** [comment]
Implemented in https://github.com/DependencyTrack/frontend/pull/801

**Comment by jcbvm** [comment]
Can this issue be reponend? I just tested this with my reverse proxy, but the base path in the project URL's are still duplicated.

When hovering over a project name the correct URL is shown ('https://domain.tld/**dtrack**/projects/3180e72b-3376-4262-9fdb-e9d040eca3fc'), but when clicking the navigation goes to 'https://domain.tld/**dtrack/dtrack**/projects/3180e72b-3376-4262-9fdb-e9d040eca3fc'. 

I'm running it containarized with **BASE_PATH** set to **/dtrack/**
