### ISSUE TITLE
Ad blockers are blocking graphs

### ISSUE THREAD

**Issue by niklaskeerl** [DependencyTrack/frontend#224]
Hey, I have not found this error in another thread and hope it is not a duplicate. I hope it is correct that I use the frontend repository for this as this only happens when using the service with a browser. 

### Current Behavior:

The firefox extensions "Adblocker Ultimate" and "Ghostery" are blocking requests to the following URLs:

``https://dependencytrack-frontend.com/api/v1/metrics/project/<ProjectUUID>/current``

``https://dependencytrack-frontend.com/api/v1/metrics/project/<ProjectUUID>/days/90``

``https://dependencytrack-frontend.com/api/v1/metrics/portfolio/90/days``

### Steps to Reproduce:

1. Use the Firefox Webbrowser

2. Install "Adblocker Ultimate" or "Ghostery" from the Recommended Extensions 

3. Go to Dependency-Track frontend and see missing graphs

### Expected Behavior:

Graphs should be visible as they are no ads.

### Environment:
  
  - Dependency-Track Version: apiserver v4.5.0, frontend v4.5.1
  - Client Browser: Firefox 103.0 (64-bit)
  - Client O/S: Ubuntu 20.04.4 LTS

### Additional Details:

Unfortunately, this addon does not let me log which filter was responsible for blocking the URLs above.

Ghostery is telling in detailed view that it found a tracker in these URLs.

PS: Thank you for maintaining such an important service for IT security. If this is too much to investigate, then maybe a quick message on the documentation could help to warn other users.

**Comment by lsauer** [comment]
Hi,
I think it is good that you reported that, so people can find this issue through google and check instant resolutions themselves. The Adblockers allow you to trust a site or wildcard domain. 
As such there is nothing to fix here. People should suggest whitelisting DT domains to the Adbocker manufacturers.

**Comment by niklaskeerl** [comment]
This was all clear to me, I wanted to make sure it is a false positive and wanted to see if it is possible to do something about it besides setting it on the whitelist. As this is not the case, I think this issue can be closed.
