### ISSUE TITLE
Show tag filter on projects page

### ISSUE THREAD

**Issue by niklaskeerl** [DependencyTrack/frontend#234]
### Current Behavior:

Currently, it is not possible to show the tag which one gives to a project in the projects overview page.

![Screenshot from 2022-08-23 11-03-18](https://user-images.githubusercontent.com/33728607/186118372-2c35fe8d-9627-4acc-92c2-7e38496fc13c.png)

### Proposed Behavior:

Add another field for the tag so you can easily search through projects with the same tag, it does not necessarily have to be enabled by default like all other fields.

**Comment by sephiroth-j** [comment]
This was fixed in #319.
