### ISSUE TITLE
Frontend not working on Firefox or Edge

### ISSUE THREAD

**Issue by brvheem** [DependencyTrack/frontend#34]
The new frontend in the latest version of dependency track is only working on Google Chrome.

**Comment by tdillan** [comment]
I can confirm this isn't working in the ESR version of Firefox I'm using (major version 68), since it lacks support for `Promise.prototype.finally`.  Would polyfilling that feature resolve the issue?

**Comment by stevespringett** [comment]
I've confirmed this to be an issue with Edge (legacy), although new Edge should work fine. 

I've also confirmed the fix works on Edge (legacy). I have not confirmed or tested with ESR FireFox, but I would assume it should work as well. If so, then this issue should be resolved in the next release of Dependency-Track, v4.0.
