### ISSUE TITLE
Remember user preferences

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/frontend#348]
### Current Behavior

There are several options a user can set on the UI to adjust views to his needs. Unfortunately, none of these are stored and once the view is left the preferences are not remembered.

### Proposed Behavior

Following preferences should be remembered for the user. This shall not be a global setting for everybody, but at least for the users local browser this preferences should be saved. They can be stored in browsers localStorage, no need to save it on server side in my opinion.

**Options to remember:**
- Number of entries shown in tables (seperate for each type of view with a table)
- Columns selected to be shown in a table (seperate for each type of view with a table)
- Some toggles, e.g. the "show inactive projects" toggle, the new "hide other components"-toggle in the graph (when opened for a component)

**To be ensured:**
The stored preferences must be fail-safe in case something changes, e.g. an option is no longer available, or especially for tables, if columns are no longer available it must not fail but ignore this column. Newly added columns, that were not existing when preferences got saved, should be shown by default, so new features are visible to everybody.

**References:**
There was a request for one of the toggles to be remembered as part of https://github.com/DependencyTrack/dependency-track/issues/1601 but since this covers a lot more topics I created a new entry to define it, also its a frontend issue in the backend ticket.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by rkg-mm** [comment]
We will take care of this

**Comment by msymons** [comment]
> We will take care of this

Thanks, @rkg-mm.   I have added this to 4.8 milestone...  so please shout if this is "too soon".
