### ISSUE TITLE
Project page version dropdown displays only 10 options

### ISSUE THREAD

**Issue by ariyonaty** [DependencyTrack/frontend#397]
### Current Behavior

When on a page for a specific version of a project that has more than 10 versions, only 10 versions are displayed in the dropdown (see image for more clarity).

![image.png](https://user-images.githubusercontent.com/18715356/215225259-d5683883-e75a-4191-a10d-ffc02e42e406.png)

For example: 

Project Name: `abc`
Project Versions: {v1..v12} 

The version dropdown will only display 10 of the 12 versions. 

### Steps to Reproduce

1. From the /projects page, navigate to a specific project/version that has more than 10 versions published. 
2. When on that page, select the dropdown listed next to the version name
3. Observe that only 10 versions are listed

### Expected Behavior

Expectation is that the dropdown contains all versions of the project.

### Dependency-Track Frontend Version

4.7.0

### Browser

Google Chrome

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
What will it look like with 63 versions?

**Comment by ariyonaty** [comment]
@valentijnscholten - I'd image similar to screenshot above, displaying 10 versions at a time, however with the addition of a "scroll bar" in the project version dropdown area that allows the user to scroll through all 63 project versions.
That said, I have zero frontend experience, so I'll defer to those more familiar with UX/UI.

**Comment by valentijnscholten** [comment]
I was actually meaning to post my comment on the PR, which I will do now.
