### ISSUE TITLE
Disable / Remove Login (Username and Password) when using OpenID

### ISSUE THREAD

**Issue by jarosith** [DependencyTrack/frontend#429]
### Current Behavior

When using OpenID to login to the Frontend UI the login field is present when using OpenID. This causes confusion for end users who are using SSO . 
![image](https://user-images.githubusercontent.com/22876251/221928721-15920b05-1353-4cfb-930a-948045fd7e68.png)

### Proposed Behavior

Option to disable/hide prompt for username and password when an SSO technology is in place 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by mieliespoor** [comment]
Yes, although there should still be a way to login using basic credentials.

**Comment by valentijnscholten** [comment]
For my users the confusion is more in the error message about the missing username, sometimes you have to click the SSO button twice to get it to work.

**Comment by syalioune** [comment]
It could be a two steps action :
- First, the UI displays just two buttons `Login with DT`, `Open ID`
- If user click on `Login with DT`, the classic form appears
- if user click on `Open ID` or whatever text is configured, he is redirected to the provider page
