### ISSUE TITLE
Replace vue2-org-tree by d3.js

### ISSUE THREAD

**Issue by walterdeboer** [DependencyTrack/frontend#443]
### Current Behavior

vue2-org-tree is being used for the dependency graph, but it's not compatible with vue3 blokking a possible upgrade later

### Proposed Behavior

Replace vue2-org-tree bij 3d.js to display the dependency graph

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
Why not patch vue2-org-tree so that its compatible with Vue3? I think that would be much easier that trying to implement d3.

**Comment by walterdeboer** [comment]
Looks like someone did that already: https://www.npmjs.com/package/vue3-blocks-tree

After some investigation d3 might be less suitable than I thought..
