### ISSUE TITLE
Export functionality to download metrics from components and vulnerabilities

### ISSUE THREAD

**Issue by nvcastelli** [DependencyTrack/frontend#500]
### Current Behavior

The data we have in Dependency Track is used to share component, vulnerability and other information to our stakeholders. Since we need a way to transfer this information to other users we have the use case for us to be able to download some of this information in a readable way and share it with our colleagues.

### Proposed Behavior

If we were able to implement a way to download information to a spreadsheet from certain UIs in the application that would satisfy our use case. I personally implemented a feature like this and am hopeful to include it into dependency track itself, pending input from the team. Please see an image of how it looks below and note the download button above the table in the UI.
![Screen Shot 2023-05-17 at 3 15 46 PM](https://github.com/DependencyTrack/frontend/assets/3475905/3afd7ba1-6007-4166-afae-452c6e0dd872)

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
Thanks for the suggestion. I would prefer to use the Export plugin in Bootstrap Table. It would save screen real estate and supports multiple formats.

Demo: https://examples.bootstrap-table.com/#extensions/export.html
API Docs: https://bootstrap-table.com/docs/extensions/export/

**Comment by nvcastelli** [comment]
Hey @stevespringett , thank you for your comment, my apologies for taking this long to get back with you but I've been working on implementing the export plugin into my local instance of dependency track. I wanted to get back with some of my findings and have a dialogue with you on what features this enhancement would need to be included into the application.

One of the first things I've found with the export plugin is that it only exports the data that is shown on the table. For example, if you are looking at component with 100 items and have the table view amount set to 50, the export plugin only downloads the 50 items that are shown on the table. We were hoping that we'd be able to pull all of the data for a given component instead of just what we can see in the table.

Secondly, how the plugin is shown in the Dependency Track UI is causing some issues that I've opened a [ticket](https://github.com/hhurz/tableExport.jquery.plugin/issues/366) against the repo that maintains the plugin. l'm not sure if this is something on my end that just needs configuration or if it's something the export plugin will need to handle. I'm waiting for their response now.

Please let me know if there's any clarifications that I can make, thanks.

**Comment by nvcastelli** [comment]
Thank you, Steve. I was able to implement that functionality. 

As it stands, using bootstrap-table-export, I am able to download files from the table. However I am still working through my second point I mentioned above where I am seeing issues in the UI. I am hoping to receive a response from the plugin team but am looking into it on my end as well. I hope to be able to contribute this to the project soon pending approval.

**Comment by stevespringett** [comment]
@melba-lopez I would like the plugin architecture to be used which would simply make the export part of bootstrap table, however, if we want to create a custom plugin to do this, thats fine with me.
