### ISSUE TITLE
Project external references are removed when updating the project using the frontend

### ISSUE THREAD

**Issue by rylyade1** [DependencyTrack/frontend#503]
### Current Behavior

Updating a project using the frontend (in the project view click on "View Details" > "Update") removes "External References" values of that project. Looking at the request payload, it does not contain the "externalReferences" property (see screenshot below
![image](https://github.com/DependencyTrack/frontend/assets/12633674/88b270cc-6849-4863-9d09-3b863e5acc85)

### Steps to Reproduce

1. Open a project which has external references.
2. Click on "View Details"
3. Click on "Update"
4. Click on "View Details" again.
5. Click on the Tab "External References". This shows an empty list.

### Expected Behavior

The external references shouldn't be removed when updating a project.

### Dependency-Track Frontend Version

4.8.1

### Browser

Google Chrome

### Operating System

macOS

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Whoops, this is indeed a frontend issue, I overlooked your analysis @rylyade1. Thanks for providing this info, super helpful!

Reopening as it requires a frontend fix.
