### ISSUE TITLE
Usability Improvement: Add "Show in Dependency-Graph" Button in "Affected Projects" List

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/frontend#533]
### Current Behavior

Feedback from our project users:
The current workflow is:

1. Get email of new vulnerability
2. Open "Vulnerability link" from mail
3. Read vulnerability details
4. Question yourself where this dependency is coming from
5. Switch to "Affected Projects" tab and select a project
6. Now you are in the Dashboard of the project
7. Switch to Vulnerabilities tab [Alternative: Components tab]
8. Find the vulnerability in the list of vulnerabilities [Alternative: Find affected component] - if you remember the details you need to identify it, otherwise go back to step 3...
9. Click "Show in Dependency-Graph" - now you see where the vulnerability is coming from

### Proposed Behavior

- Add a "Show in Dependency-Graph" directly in the list of affected projects tab in the vulnerability information
- Optional addition: When clicking the link of an affected project in the "affected projects"-tab, open the vulnerability tab of that project instead of the dashboard, ideally expand the vulnerability immediately and scroll to it, so user can directly start analysis decisions etc.

Expected Workflow:
1. Get email of new vulnerability
2. Open "Vulnerability link" from mail
3. Read vulnerability details
4. Question yourself where this dependency is coming from
5. Switch to "Affected Projects" tab and click **"Show in Dependency-Graph" Icon** from the project
6. Now you see where the vulnerability is coming from

Very small change but would increase user acceptance in projects a lot from what I hear, as this workflow is the most used one and feels unnecessary complicated with some frustration on the path

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Great suggestion!

**Comment by nscuro** [comment]
Implemented in #667. Thanks @rkg-mm!
