### ISSUE TITLE
Make redirect functionality with OIDC flow configurable

### ISSUE THREAD

**Issue by cnocula-i** [DependencyTrack/frontend#64]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
The PR https://github.com/DependencyTrack/frontend/pull/47 introduced a functionality to redirect the browser to a protected URL. In the documentation it is stated, that a wildcard needs to be used in the callback to allow multiple targets as in:
`https://dependencytrack.dev.ibmega.net/static/oidc-callback.html*`

Unfortunately, we are using the Dex (https://github.com/dexidp/dex) as a provider for single sign on with our GitHub Enterprise, which does not support having wildcards in their `redirectURIs` configuration.

I tried to register at least the entrypoint as `https://dependencytrack.dev.ibmega.net/static/oidc-callback.html?redirect=/dashboard`, but that leads to a white browser page (oidc-callback.html) with a JavaScript error on the console. It would not have been practical anyway to add the whole bunch of potential redirect callbacks anyway.

I had to roll back to frontend v1.2.0

### Proposed Behavior:
Make the redirection option configurable for the frontend. When turned off, the OIDC flow should just work as in version 1.2.0 with a simple static `https://dependencytrack.dev.ibmega.net/static/oidc-callback.html`

**Comment by timmahj** [comment]
This is also an issue with Okta.

**Comment by oz-viadee** [comment]
Also an issue with Microsoft Azure AD

**Comment by Stephan84** [comment]
Also with on premises Microsoft ADFS

**Comment by erwanosouf** [comment]
Also with Google

**Comment by axelspangberg** [comment]
We're also having the same issues using ORY Hydra - they do not allow any wildcards in the redirect_uri

**Comment by jsaalfeld** [comment]
And with self-hosted gitlab.
