### ISSUE TITLE
Switch Between Project Versions Gives HTTP 404 for all but Overview Tab

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/frontend#641]
### Current Behavior

Switching between project versions gives an HTTP 404 unless the current tab being viewed is "Overview".

### Steps to Reproduce

1. Navigate to project that has more than one version.
2. On Overview tab, use version dropdown to switch to another version.  Success.
3. Click on any other tab.  eg Components.
4. Use version dropdown to switch to another version of project.  HTTP 404.

![image](https://github.com/DependencyTrack/frontend/assets/4938718/80ee1387-e833-446d-a4f6-d4dd433ca395)

Problem is that (using Components tab as example) switch should be from:

`https://dependency-track.foo.bar.com/projects/xxx/components`

to:

`https://dependency-track.foo.bar.com/projects/yyy/components`

...but is actually to:

`https://dependency-track.foo.bar.com/projects/xxx/yyy`

Tested on DT v4.9.1 and also on v4.10.0-SNAPSHOT

### Expected Behavior

There should be no HTTP 404 errors when switching from one version of a project to another, no matter what tab is being viewed.

When switching,  the tab should remain unchanged.

### Dependency-Track Frontend Version

4.10.0-SNAPSHOT

### Browser

Mozilla Firefox

### Browser Version

119.0

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by rkg-mm** [comment]
I actually just found this and fixed this in another PR https://github.com/DependencyTrack/frontend/pull/658

**Comment by nscuro** [comment]
@rkg-mm Awesome! The whole of #658 will not make it into 4.10 anymore, but a fix for this bug we can still include. Would you be willing to split it into a separate, smaller PR?

**Comment by rkg-mm** [comment]
@nscuro  done
