### ISSUE TITLE
Aliases column is not displaying information in Vulnerabilities section

### ISSUE THREAD

**Issue by LaVibeX** [DependencyTrack/frontend#765]
### Current Behavior

When a vulnerability has an alias, the column displays no information. This issue arises from a problem in the frontend code, specifically in line <73:VulnerabilityList.vue> const aliases = common.resolveVulnAliases(value); where the function expects both the vulnerability source and the vulnerability alias, but only receives one parameter.

![image](https://github.com/DependencyTrack/frontend/assets/52439101/de3202da-54e2-44d7-8230-ef76c4b31e3a)

### Steps to Reproduce

1. Go to the Vulnerabilities Section
2. Activate Alias
![image](https://github.com/DependencyTrack/frontend/assets/52439101/3ff1ce11-c31e-4faf-890d-67eecc9e0941)

3. If a vulnerability has any aliases, the Aliases column does not display them.

### Expected Behavior

Aliases Column displaying the alias assigned to that vulnerability in Vulnerabilities Section. 
![image](https://github.com/DependencyTrack/frontend/assets/52439101/6d76e289-3124-480f-be51-bac8094dd13e)

### Dependency-Track Frontend Version

4.7.x

### Browser

Google Chrome

### Browser Version

Firefox

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Closed via https://github.com/DependencyTrack/frontend/pull/766
