### ISSUE TITLE
Migrate Docker image from Alpine to Debian Slim

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/frontend#78]
Alpine images can cause some incompatibility issues due to its use on musl instead of glibc.

This ticket is to track the migration of the Dockerfile from using an Alpine base image to one based on Debian slim.

Related to https://github.com/DependencyTrack/dependency-track/issues/1054

API Server: https://github.com/DependencyTrack/dependency-track/issues/1090

**Comment by k3rnelpan1c-dev** [comment]
If I may have a comment/feedback here:
You use Nginx here as a container base to serve 'pre-compiled' static Vue pages. Nginx has no problems running under Musl, unlike most JVMs and officially supports/compiles against Musl (for what I know). Migrating the frontend container to a larger in size base with a larger attack surface seems not ideal therefor IMHO.
You can always offer both versions a Alpine and a Debian one, the maintenance of that should be trivial and CI for that is easily configured. (I can offer a proposal for that if you are interested)

Anyway, this obviously represents just my two cents and you are welcome to disregard them, I just wanted to point this out.
