### ISSUE TITLE
Improve contrast ratio for the progress bars.

### ISSUE THREAD

**Issue by validide** [DependencyTrack/frontend#814]
### Current Behavior

Currently the progress bar text used for displaying the policy violations and vulnerabilities is white which, for me at least, makes it difficult to read.

![image](https://github.com/DependencyTrack/frontend/assets/5551616/7f6f3d95-e53e-49b6-9303-37ea1cec9533)

### Proposed Behavior

The suggestion is to change this to black.

I am willing to do the change and create a merge request I just need to know if this is something the project would accept.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by setchy** [comment]
> I wonder if the font color should be dependent on the color of the background. While white is hard to read on yellow background, black might be hard to read on a grey one.
> 
> Thoughts on this @setchy @msymons?

I agree with having text-color based on the background.

The example shown at https://getbootstrap.com/docs/5.3/components/progress/#backgrounds displays this.  Looks to be as simple as adding the `text-dark` class...

![Screenshot 2024-04-15 at 9 22 26 AM](https://github.com/DependencyTrack/frontend/assets/386277/729a7dce-846d-442a-9128-59a31f9f0222)

**Comment by validide** [comment]
Isn't the frontend using Bootstrap 4-ish (BoostrapVue)?

This is just with the `text-dark` class

![image](https://github.com/DependencyTrack/frontend/assets/5551616/6a41f73e-3a7e-4d26-9a01-cd5b6ca7e62c)

And this with `text-dark` and ``

![image](https://github.com/DependencyTrack/frontend/assets/5551616/e50b7199-208a-4790-b652-00af731bd682)

**Comment by setchy** [comment]
> Isn't the frontend using Bootstrap 4-ish (BoostrapVue)?

Yes it is.  Was just using as an example 🙃

**Comment by validide** [comment]
I'm ok with implementing either way, just let me know if it should be dependent on the background and if I should make the text bold.

**Comment by setchy** [comment]
I'll take @nscuro lead, but I think we'll need text colors based on background since the examples shared above for gray progress bars are hard to read

**Comment by nscuro** [comment]
> @setchy [...] but I think we'll need text colors based on background since the examples shared above for gray progress bars are hard to read

Agreed.

**Comment by validide** [comment]
This is the version I have now.

![image](https://github.com/DependencyTrack/frontend/assets/5551616/62f74fdd-e93d-4aee-8518-70e45b7efdfd)

I am not quite sure of the white text on the green background. If you have other suggestions let me know.
