### ISSUE TITLE
Add EPSS conditions to policies

### ISSUE THREAD

**Issue by 2000rosser** [DependencyTrack/frontend#896]
### Current Behavior

https://github.com/DependencyTrack/dependency-track/pull/3746
The PR above contains the back end implementation for using EPSS in policies.
There is no front end implementation yet.

### Proposed Behavior

The front end should allow the user to use EPSS conditions in policies

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
This was implemented in #930.
