### ISSUE TITLE
Usability of VulnerabilityAudit

### ISSUE THREAD

**Issue by markusmuellerusi** [DependencyTrack/frontend#897]
### Current Behavior

Please refer to
https://github.com/DependencyTrack/dependency-track/issues/3841

It would be necessary to update front- and backend.

![Audit](https://github.com/DependencyTrack/frontend/assets/11981532/672c4a0d-6065-4c89-9b42-2ec2e621103c)

Add EPSS score and EPSS Percentile to column list (frontend, backend supplies necessary columns already)
Put from-to-filter-fields in one row (please see date fields)
Use a checkbox and a multi-range-slider for CVSSv2, CVSSv3 and new fields EPSS score and EPSS Percentile. The checkbox shows and hides the slider, and is responible for adding them to querystring.
Make data types of these fields "number". The checkbox value is better than an empty or non-emty "string".
Put CVSSv2, CVSSv3, EPSS score and EPSS Percentile on top of all filters. This are the criteria really used for audits, not comments, vendor responses, dates and text searches.

### Proposed Behavior

Provide EPSS score and EPSS Percentile
Think about, how companies would define their risk appetite.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Closing this as duplicate since we already have https://github.com/DependencyTrack/dependency-track/issues/3841.

If something needs work in both API server and frontend, we usually have one issue in the API server repo, and reference it from PRs we create in the frontend repository.

Thanks for the great suggestions!
