### ISSUE TITLE
Cannot display Tooltip info for latest point on graphs

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/frontend#92]
### Current Behavior:

When hovering the mouse pointer over any graph in Dependency-Track (the main dashboard has the most graphs) then one can point at "now" (the point on the far right of any graph) and yet the tooltip data only shows info from a few days ago.

![image](https://user-images.githubusercontent.com/4938718/130443277-b288c584-5ef9-47e2-80f7-6d7d4a85c601.png)

![image](https://user-images.githubusercontent.com/4938718/130444176-29a1b3fa-f8ae-4b55-96c5-5289798b8aec.png)

### Steps to Reproduce:
Wave your mouse pointer over any DT graph.  When pointing at the right-most point on any graph,  the displayed tooltip data is not current,  It represents a point on the graph to the left of where your mouse is pointing.

Using Zoom (in or out) does not help.

### Expected Behavior:
Mouse-over should support displaying data relevent to whatever point on on the graph the mouse is hovering over,

### Environment:
  
  - Dependency-Track Version: 3.8.0, 4.3.3
  - Client Browser:   Firefox, Chrome, Microsoft Edge
  - Client O/S: Windows 10, Mac.

**Comment by sekwah41** [comment]
Seems for some reason it thinks the mouse pointer is further over than it actually is.

Also found this on linux using chrome

![image](https://user-images.githubusercontent.com/3209834/150655929-42604431-6f6f-45d0-9fc3-ea61eb1cf187.png)

Also looks like it may be the same issue as https://github.com/apertureless/vue-chartjs/issues/526

**Comment by sekwah41** [comment]
Found the issue. the point `hitRadius` is far too large so what it does is the library doesn't go for the closest point it goes for the furthest left which hits its desired effect.
