### ISSUE TITLE
"Add Version" Create Button Should Be Inactive Until Version Provided

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/frontend#995]
### Current Behavior

In the Frontend, a new project version can be created via `View Details` -> `Add Version`

The resulting dialog has a create button that is active.  Clicking it without providing a Version string will result in an HTTP 400 error and some 190 lines of exception logging in the server log, starting with...

```
2024-09-15 19:08:46,561 ERROR [ServerRuntime$Responder] An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:649)
```

If an admin is looking at the logs then they have absolutely no context for what caused the exception.

### Proposed Behavior

The "Create" button should be inactive until something has been provided in the "Version" field.  

![image](https://github.com/user-attachments/assets/e6885fc8-cd82-486b-a89b-2a7b585a43d7)

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this enhancement was already requested

**Comment by IdrisGit** [comment]
Hi, I think it should also have a backend validation for the request body to check if the version value is provided and correct, however, a client-side validation is very useful from the UX and the program side.

I can look into this issue, does this issue need to be assigned to me or can I fix and open a PR for it? Please let me know.

**Comment by msymons** [comment]
@IdrisGit,  you can normally just start working on an issue and submit a PR, but assigning the issue to you is a process improvement because then others can see that the issue is "spoken for".   That's especially valuable right at the moment during [Hacktoberfest](https://hacktoberfest.com/).

Are you participating in Hacktoberfest?  If you are not then let us know and the hackoberfest label can be removed from this issue.

**Comment by IdrisGit** [comment]
Sure, I will start working on it. 
I am participating in the Hacktoberfest and hoping to use it as an opportunity to get into the world of Open Source as a contributor.

**Comment by IdrisGit** [comment]
I am trying to setup and test out my changes locally, I am able to launch the dev server for the frontend and the backend, frontend requires login credentials, are there any default values or a bypass method that I can use to test locally, or do I need to setup the database and users table?

**Comment by IdrisGit** [comment]
I have opened a PR that fixes the issue. Please let me know if any changes are required or if you need any additional details from me.

Also, I noticed that the version input field is optional when creating a new project. Is this intentional, or is a version value required when a new project is created?
![Image](https://github.com/user-attachments/assets/26126853-11b9-49c0-b4fe-c6412ffded8c)

If it is not intentional and the version is required let me know, I can work on that part and raise a new PR or update the existing PR.

**Comment by msymons** [comment]
@IdrisGit, thanks again for the contribution.

> Also, I noticed that the version input field is optional when creating a new project. Is this intentional, or is a version value required when a new project is created?

It is intentional.  Or, rather, it perhaps "was originally intentional" in the days before the ability to clone a project was introduced.

I have several projects in my production system that have been created without versions and they all work perfectly fine.

I am sure that things can be improved and things might be re-evaluated in the future after collection projects, etc, are introduced.

Having said that, I have tested new project creation and perhaps logging can be improved.

**Comment by IdrisGit** [comment]
Let me know if there some task that I can look into for the project creation and logging.
